### PR TITLE
Add support for TRANSLATION element to PTC

### PR DESCRIPTION
**Pull request by jsberg-bnl**
See my comment on issue 891. This doesn't solve everything, but at least PTC can deal with TRANSLATION.

### CODE REVIEW

**Comment by tpersson** [comment]
I didn't manage to check continue on your branch so I simply took your changes and added the tests that we need and fixed some small other things and made a new PR

**Comment by tpersson** [comment]
Thanks a lot for the help and we plan to include the features you connected in the next release.

**Comment by madcern** [comment]
This is now implemented in PR #957 which is merged into master. Do you think you could check that this works according to what you expect?

**Comment by jsberg-bnl** [comment]
Sorry to take a while getting back to you on this, I've been doing a few checks and running into trouble. PTC_TWISS is working well in all the checks I've done so far. However, there are problems with TWISS (and presumably TRACK) handling both YROTATION and TRANSLATION. Essentially SURVEY and TWISS seem to do the opposite thing, but SURVEY and PTC_TWISS agree. See this example: [201201a.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5630538/201201a.txt). It's just geometry and a drift, so the orbit should come back to x=0 and px=0. Survey does the right thing, so does PTC_TWISS, but both the translation and rotation in TWISS do the opposite of what would agree with SURVEY.

**Comment by tpersson** [comment]
@jsberg-bnl I will have a look and get back to you the latest at somepoint beginning next week.

**Comment by tpersson** [comment]
I so far have only had a look at translation but there it all seem to be consistent to me. You can have a look at the example:
https://github.com/MethodicalAcceleratorDesign/MAD-X/blob/master/tests/test-translation/test-translation.madx

**Comment by jsberg-bnl** [comment]
Looking more carefully, I agree TRANSLATION is fine. It's YROTATION where the problem lies. With a positive angle, SURVEY shows a positive THETA, and TWISS shows a positive PX; they should have opposite signs. See the example file I attached above, which only contains drift space: the survey returns to x=y=theta=0, and therefore the coordinates from TWISS should be zero; but the TWISS run shows nonzero coordinates (but PTC_TWISS does give zero with the new code).

**Comment by tpersson** [comment]
I also think that the rotation in survey is wrong sign but I think TWISS is doing the same both in PTC and MAD-X. I have double checked all the rotations again in PTC and MAD-X and I get the same sign from all of them. Your example doesn't fully worked for me (not even in PTC) so I made some modifications, see below.

I will change the Y-rotation in Survey in a PR that will come soon which will also contain some other features including the posibility to add permanent offsets of element (which you now have to do with errors). 



beam, particle=proton, energy=275;
a := 0.01;
l := 2;
o: drift, l=l;
yp: yrotation, angle := +a;
ym: yrotation, angle := -a;
xd: translation, dx=l*sin(a);
myseq: sequence, l=5;
yp, at = 1;
ym, at = 1+l; 
xd, at = 1+l;
endsequence;


use, sequence=myseq;
select, flag=twiss, column=name,keyword,s,l,angle,x,px,dx,dpx,betx,alfx,bety,alfy;
select, flag=ptc_twiss, column=name,keyword,s,l,angle,x,px,disp1,disp2,beta11,alfa11,beta22,alfa22;
twiss, file="201201a-twiss.tfs", betx=1, bety=1;
survey, file='201201a-survey.tfs';
ptc_create_universe;
ptc_create_layout, model=2, method=6, nst=5;
ptc_twiss, icase=5, no=5, x=0, px=0, y=0, py=0, betx=1, bety=1, file='201201a-ptc.tfs';

**Comment by madcern** [comment]
I think that YROTATION in SURVEY is correct. It must have the opposite sign of ANGLE in SBEND and same sign as DTHETA in EALIGN. I attached slides that I used to crosscheck MAD-NG with a chicane (slides 4 and 5) and the YROTATION of MAD-X was correct at that time (~2 years ago).
[ld_1901-mad_tilt_slides.pdf](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5696336/ld_1901-mad_tilt_slides.pdf)

**Comment by ldeniau** [comment]
I think that YROTATION in SURVEY is correct. It must have the opposite sign of ANGLE in SBEND and the same sign as DTHETA in EALIGN. I attached slides that I used to crosscheck MAD-NG with a chicane (slides 4 and 5) and the YROTATION of MAD-X was correct at that time (~2 years ago).
[ld_1901-mad_tilt_slides.pdf](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5696365/ld_1901-mad_tilt_slides.pdf)

**Comment by jsberg-bnl** [comment]
> I also think that the rotation in survey is wrong sign but I think TWISS is doing the same both in PTC and MAD-X. I have double checked all the rotations again in PTC and MAD-X and I get the same sign from all of them. Your example doesn't fully worked for me (not even in PTC) so I made some modifications, see below.

I just re-ran my example on master and yes, I see TWISS and PTC_TWISS agreeing. I must have run a different region than I thought I did (maybe with my patch?). It was the sign flip in your commit 4a02b291 that made them agree. 

Strangely, my example runs fine even with the latest master (16bd8913). Here's the output: [201201a-ptc.tfs](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5696681/201201a-ptc.txt), [201201a-survey.tfs](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5696682/201201a-survey.txt), [201201a-twiss.tfs](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/5696683/201201a-twiss.txt).

As long as survey and twiss (and everything else) give consistent results, I suppose the sign convention is irrelevant. Note that the documentation of YROTATION is not consistent: the equation for the transformation of the coordinates is not consistent with a clockwise rotation of the coodinate axes (at least when viewed from above): s=0 x>0 should result in s<0 after the coordinate system is rotated clockwise.

**Comment by ldeniau** [comment]
You are right, it should be written counterclockwise.

**Comment by ldeniau** [comment]
I put here some extra information to clarify the situation, please let me know if you see something incorrect. This has been cross-checked between MAD-X and MAD-NG two years ago, and the details are in the slides attached to a previous comment in this thread.

In **Survey**, the following conventions and definitions are used (in all MAD8, MAD9, MAD-X, MADX-PTC, and MAD-NG).
1) Elements define the design orbit of the local frame in the global frame. Transformations applied to the design orbit or to the element are the same and reflect the change of the local frame in the global frame (translation and orientation).
2) The only elements that change the design orbit from the straight line is the S,R-BEND with its angle (and tilt), and all the patches.
3) S,R-BEND element with angle>0 turns right when looking in the backward direction of Y-axis (from the top), this is an old-standing CERN convention.
4) X,Y,S-Rotation patches are trigonometric rotations and turn counter-clockwise when looking in the backward direction of their rotation axis.
5) X,Y,S-Translation patches are standard translations and translate along their axis with the same sign (positive dx increase x).
6) Misalignments displace the element vs the design orbit on entry and restore it on exit using patches as-is. Hence misalignments do not change the design orbit, but can be visualized inside element (by slicing in MAD-NG). The only sign change is on dphi (elevation angle) when computed with x-rotation. The details of the equations are in the slides 11-17 with examples of application and plots.

In **Track and Twiss** in the local frame moving on the desing orbit, the inverse transformation done in Survey are applied to the tracked particles, i.e. reverse the signs and the order of application. In particular, here misalignments will have to cancel the transformations done by Survey on the local frame, such that tracked particles have continuous motion in the global frame.

Unless I forgot something, with these definitions and conventions, there is only one way to do things right.

The initial confusion was probably coming from:
- In Survey we often look (for horizontal machine) at the global frame in the X-Z plane looking in the forward Y, where positive X goes right.
- In Track and Twiss we look at the local frame in the x-y plane looking in the forward s (z), where positive x goes left.

So both frames are right-oriented (a must-have!) and therefore are the SAME, i.e. local coordinates can be added to global coordinates once local and global frames are superposed, that is the local frame is properly translated and oriented in the global frame using the Survey translation vector V and orientation matrix W. I have examples plotting beta functions in the global frame, all around the machine (also ploted) using Survey and Twiss table data (in MAD-NG).

So for me, the case is closed unless one provides an example that breaks one of these conventions and definitions. Still it's possible that errors remains in the manual...

**Comment by jsberg-bnl** [comment]
Just to clarify, the issue I'm talking about in these last few posts is that (in the example I gave) survey says that the coordinate axes return to the z axis (x=0, theta=0), but for twiss (and presumably track) in a system with a drift and a particle launched along the z axis (x=0, px=0), the final particle coordinates are nonzero; thus survey and track/twiss disagree on the sign of a y rotation at the moment.

**Comment by jsberg-bnl** [comment]
I'm going to close this pull request for now. There is still an issue with `yrotation` in `twiss`, I'll open that up as a separate issue.

**Pull request closed without merging**
