### PR TITLE
Chrom command gives chromaicity in PT + fix of weak focusing in TWISS

### PR DESCRIPTION
**Pull request by tpersson**

### CODE REVIEW

**Comment by rdemaria** [comment]
Question: do you pass angle and k0 to PTC separately? This is to check if the case of angle!=k0l is managed well by PTC

**Comment by tpersson** [comment]
No the angle is not transferred to PTC. I had a look since tI wanted to have the tapered lattice also in PTC. I think it should be quick to fix, since it is effectively the same thing as an error .

**Comment by rdemaria** [comment]
I think it is important also for the sake of making comparisons..

**Comment by tpersson** [comment]
I agree. I thought it was taken care of when this was implemented but I guess it was forgotten..

**Pull request merged**
