### PR TITLE
Travis CI configuration

### PR DESCRIPTION
**Pull request by coldfix**
Without coverage so far.

### CODE REVIEW

**Comment by coldfix** [comment]
Can you also enable MAD-X on the Travis website?

**Comment by ldeniau** [comment]
Need to discuss…

**Comment by kyrsjo** [comment]
Let me know when you have it operational; this would be interesting to copy for SixTrack as well...

**Comment by coldfix** [comment]
It is. It just wasn't enabled on the repo until now.

**Pull request merged**
