### PR TITLE
Fix aperture plot

### PR DESCRIPTION
**Pull request by coldfix**
Hi,

this contains the fix for the bug introduced by #429 that Laurent described by mail to me: plotting the aperture table results results in a plot that stops at the first interpolated element. The reason is that the plotting routine works with `advance_to_pos` which uses `table::p_nodes` which were pointing to the temporary (invalid) nodes. With the fix, the table entry will always point to the template node that was used to interpolate the current node.

However, note that with this patch, while generating the expected plot, the example produces new warnings:

```
++++++ warning: double_from_table_row: column not found: aperture->k1l
++++++ warning: double_from_table_row: column not found: aperture->k1sl
++++++ warning: double_from_table_row: column not found: aperture->k2l
++++++ warning: double_from_table_row: column not found: aperture->k2sl
++++++ warning: double_from_table_row: column not found: aperture->k3l
++++++ warning: double_from_table_row: column not found: aperture->k3sl
```

for each interpolated node. These come from `plot.f90` line 462-470 (in `pefill`).

The reason is that with the patch, `currtyp = node_value('mad8_type ')` is (correctly?!) deduced as the value `5` (which means `code_quadrupole`, according to `util.f90`), and apparently the aperture table does not contain the required columns. Before #429, the `currtyp` was `1` (drift) for all interpolated nodes.

So, there are two plausible fixes:
- in `pefill` check if the table contains the required columns and skip the if-case otherwise
- add these columns to the aperture output table 

IMO, the best solution is to do both. What do you think?

Best, Thomas

Example to reproduce:

```fortran
!----generic test sequences----------------------------------------
KQ1 = 0.01;
KQ2 = -0.01;

testseq: SEQUENCE, l = 50.0;
  MQ1.s: QUADRUPOLE, K1=KQ1, l= 2, at=15, APERTYPE=CIRCLE, APERTURE={0.02};
  MQ2.s: QUADRUPOLE, K1=KQ2, l= 2, at=45, APERTYPE=CIRCLE, APERTURE={0.02};
ENDSEQUENCE;

BEAM, PARTICLE=PROTON, ENERGY=7000.0, EXN=2.2e-6, EYN=2.2e-6;

!---TWISS and APERTURE
USE, SEQUENCE=testseq;
TWISS, BETX=100, BETY=100;
APERTURE, file="aperture.out";

!---THIS plot works for MADX 5.03.06 but not for 5.03.07
PLOT, TABLE=APERTURE, HAXIS=S, VAXIS1=N1, VAXIS2=BETX, VMAX=110, NOLINE, NOTITLE, NOVERSION;
```

### CODE REVIEW

**Comment by ldeniau** [comment]
I will have a look to your suggestion(s). Thanks for the fix.

**Comment by tpersson** [comment]
We got a question and this again...
I think we simply shouldn't try to look for them when they are not there, which is your first suggestion.

What do you think Laurent?
________________________________

**Comment by ldeniau** [comment]
On 01 Feb 2018, at 15:57, tpersson <notifications@github.com<mailto:notifications@github.com>> wrote:

We got a question and this again...
I think we simply shouldn't try to look for them when they are not there, which is your first suggestion.

What do you think Laurent?

As a first step I agree (I implemented 2 years ago function that only checks if a column or a row exist in a table, no warning). Would these values be useful in aperture table?

Cheers,
Laurent.

________________________________

**Comment by ldeniau** [comment]
Finally, I choose to disable the warnings instead of testing for the column because the table function is pretty robust and does already the job...

**Pull request merged**
