### PR TITLE
Npart for beam beam

### PR DESCRIPTION
**Pull request by tpersson**
This implements the request in #1021

### CODE REVIEW

**Comment by coldfix** [comment]
Hi,

sorry for not responding earlier, I just realized that you are on this. What was the original error?

If you want to get newer compiler/tooling, it's probably best to to manylinux2010 or later (see https://github.com/pypa/manylinux#docker-images) rather than install the compilers manually.

Also, quick tip to speed up your debugging on GitHub Actions: Insert this step into the github action:

```yaml
   steps:
    ...
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
```

It will start up a tmate session, wait for users to connect and continuously print out an ssh address that lets you connect into the session. That makes it much easier to pinpoint problems than repeatedly changing bits and pieces and then waiting for the action to run through.

**Comment by coldfix** [comment]
Available images are listed here also: https://quay.io/organization/pypa

**Comment by tpersson** [comment]
@coldfix No worries. Thanks for your reply! This way of debugging the action looks way more convenient! I have been looking for something like that. Indeed it is probably better to upgrade but I am really a novice when it comes to the GitHub action. Thanks!!

**Comment by tpersson** [comment]
@coldfix The original problem is that one of the tests doesn't give the right results. It is a very simple call to the beambeam module and it seems that one of the parameters is not passed. I don't know for sure it is the compilers that make the difference but  compiling in with cmake locally for me an Yngve then it works nicely and then I saw that the compilers were old (and different from what I use) so wanted to try if it would make a difference.

**Comment by coldfix** [comment]
@tpersson I see. Did you confirm that it is due to one of the parameters not being passed (e.g. using printf or gdb?), or could it be just numerical errors due to different math implementation etc?

In the first case, it could maybe be related to some kind of undefined behaviour or usage of uninitialized memory..

I can take a look later or tomorrow if you pinpoint me to the function + parameter that you expect to be at fault.

**Comment by tpersson** [comment]
@coldfix Since, I wasn't able to reproduce the problem locally I couldn't use gdb or any other tools (since I didn't know about connecting to the session ). What I think happening is that the el_part is always zero in this function for some reason in this call: 
https://github.com/tpersson/MAD-X/blob/npartBeamBeam/src/madx_beam_beam.f90#L5

The difference is too big to be a numerical difference only. If this element is 0 there is no kick at all meaning that the beambeam element is not doing anything and that is excactly what we see in these failing test.

I tried a very quick test to switch to 2014 but than I got problems with the linking. 

If you have time to have a look tomorrow then I will just leave it like this and wait for your feedback. Many thanks!!  Otherwise I might try to connect and fix it.

**Comment by coldfix** [comment]
Hi,

I had a short look and think I found the problem.

It is due to the line `npart_tmp = node_value('npart')` which needs to be changed to:

```diff
-        npart_tmp = node_value('npart' )
+        npart_tmp = node_value('npart ')
```

I'll post a PR against your branch.


## Regarding the debugging

This may be helpful for future debugging:

First of all: I can reproduce the error locally by just executing the `docker` command on my PC:

```bash
docker run --rm --init -v `pwd`:/mnt -w /mnt/ quay.io/pypa/manylinux1_x86_64 .github/build_manylinux_cmake

./.github/utils/make_tests ARCH=64 TESTS=test-beambeam-npart
```

In order to more quickly rerun the build, you have to remove some lines from the build script after the first successful build, e.g.:

```diff
diff --git a/.github/build_manylinux_cmake b/.github/build_manylinux_cmake
index 285295f89..3f18a30c1 100755
--- a/.github/build_manylinux_cmake
+++ b/.github/build_manylinux_cmake
@@ -1,7 +1,6 @@
 #! /usr/bin/env bash
 set -ex
 
-mkdir build
 cd build
 
 : ${PY:=/opt/python/cp36-cp36m/bin}
@@ -11,19 +10,6 @@ $PY/cmake --version
 
 gfortran --version
 gcc --version
-$PY/cmake .. \
-    -DBUILD_SHARED_LIBS=OFF \
-    -DMADX_STATIC=ON \
-    -DCMAKE_INSTALL_PREFIX=../dist \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_C_FLAGS="-fvisibility=hidden -flto" \
-    -DCMAKE_CXX_FLAGS="-fvisibility=hidden -flto" \
-    -DCMAKE_Fortran_FLAGS="-fvisibility=hidden -flto" \
-    -DMADX_INSTALL_DOC=OFF \
-    -DMADX_ONLINE=OFF \
-    -DMADX_FORCE_32=OFF \
-    -DMADX_X11=OFF
 
 $PY/cmake --build . --target install
 
 [[ $(arch) == i686 ]] && ARCH=32 || ARCH=64
```

I then put a `print` command in `madx_beam_beam.f90` and got printed the expected value (1e12), then also added a print after the `npart_tmp = node_value('npart' )` line and noticed that I now get an incorrect value. I therefore added a printf to the `node_value()` function and noticed that it was not querying for a parameter that started with `"npart"`  but then continued with the first word from the `print` appended. At that point I recalled that fortran strings are not NULL-terminated and the problem is probably due to the two strings being stored right behind each other in memory.

The difference with the newer compilers is probably that they may decide to store extra NULL bytes in between fortran strings for your safety, but I don't think you can really rely on that. So building with the old compiler actually revealed a potential error.

**Comment by madcern** [comment]
@coldfix Many thanks for spotting my bug!! I know well this with the non NULL terminated string in Fortran and I have in fact done this in the past but then I have  spotted it since I have gotten errors or 0 and my local machine! I fully agree that it was actually good that it failed on the old compilers. 

Thanks a lot also for your explanations of how the system works. I now will be able to debug it in case I see something similar in future. It is very valuable!

**Review by madcern — APPROVED** [review]

**Pull request merged**
