### PR TITLE
Taper command finalised

### PR DESCRIPTION
**Pull request by ghislain-roy**
Please review the code and documentation. 
Tests have been updated with a full fledged test-taper that includes the tapering=true for Twiss and Match. The test-tapering test has been removed.

### CODE REVIEW

**Comment by tpersson** [comment]
Thanks! Could you just resolve the conflicts? Then the automatic testing here should be able to run as well.

**Comment by tpersson** [comment]
There seems to be some warnings on some of the platforms. It is a bit strange since I cannot see it when I compile it locally but if you for example see this run 

https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/1034/checks?check_run_id=3906911740

I am not sure if the warnings real or some problem with the setup here in GitHub but would be good to check.

**Comment by ghislain-roy** [comment]
Hello,last twoo

> I am not sure if the warnings real or some problem with the setup here in GitHub but would be good to check.

All but two of the failures in checks are due to missing docker units to run the tests. The last two failures are due to a missing input module file that should have been compiled together with the rest. Could that be a case of missing "make clean" before the actual make. 

I also noticed that some tests are run on "make tests" instead of "make tests-all" "testwhich means we are missing the "tests-long" of which "test-taper" is a part. 

I am afraid there is not much more I can do with this now. Up to you !
Cheers,
Ghislain

**Review by tpersson — APPROVED** [review]

**Comment by tpersson** [comment]
Thanks! It is now merged

**Pull request merged**
