### PR TITLE
Changed scaling in PTC TWISS and update tests.

### PR DESCRIPTION
**Pull request by tpersson**
*Changed the scaling of the TWISS functions with p0/p1 
*Results consistent with Tracking and dedicated element in MAD-X Twiss

### CODE REVIEW

**Comment by piotrskowronski** [comment]
Hi Tobias,
The 5th coordinate changes with time true/false. 
So the lines
pt_ = A_script_probe%x(5).sub.'0'
  onedp   = sqrt( one + two*pt_/relativisticBeta + (pt_**2)) 
should be within
if ( default%time ) then

else
 onedp =  A_script_probe%x(5).sub.'0'
 pt_ = ....

**Comment by tpersson** [comment]
Thanks a lot for the fast comment! I did implement the if statement but I am still a bit confused. 
I printed the A_script_probe%x(5).sub.'0' in the two cases and they came out the same after acceleration (like if they were pt). I made an example that seems to show that. Am I missing something here?


[newjob.madx.txt](https://github.com/MethodicalAcceleratorDesign/MAD-X/files/4751325/newjob.madx.txt)

**Comment by piotrskowronski** [comment]
Hi,

You will see the difference if you have 2 accelerating cavities OR cavity and radiation.

The point is here:
**++++++ warning: my_state  TIME=false with RF cavities gives approximative results valid only for fully relativistic beams (beta~1)**

PTC RF cavity changes x(5) the same way for time true and false, what is clearly wrong.
So actually if you treat it always as PT it is good enough because it is inline with the warning. 

But suggest you keep the if for correctness.

Piotr

**Comment by tpersson** [comment]
I see! I kept the if statement but removed the printing. Fine to merge?

Cheers
Tobias

**Pull request merged**
