### PR TITLE
Add kicks for multipole/bends to support k0l != angle

### PR DESCRIPTION
**Pull request by coldfix**
I have implemented this as an alternative for the specific solution suggested in #517, since we also have use for K0L!=angle, specifically in SBEND.

Note that I have added additional KICK attributes to these elements. The main reasons for this choise were:

- we prefer a modelling as geometric ANGLE, plus additional KICK. Naming the attribute HKICK should make it clear what it does. 
- in the case of MULTIPOLE, if we did use the existing ANGLE attribute as suggested in #517, it is not a priori clear what happens for skew multipoles. Is ANGLE always horizontal? Does ANGLE force that only the horizontal reference system is changed, but not the vertical one?
- in case of SBEND/RBEND, I wasn't sure about existing use of KNL/K0. Furthermore, using KNL[0] would seem to suggest that KNL[1] etc can be used as well (which is so far not implemented).

However, I'm of course open for discussion about reusing the existing KNL, ANGLE, K0 and whatnot attributes.

I have not yet checked or added tests since I wanted first to wait for the outcome of the discussion.

Best, Thomas

### CODE REVIEW

**Comment by ldeniau** [comment]
Hi Thomas,

I am taking this issue as it is a very sensitive one for backward compatible with our studies. I will do it next week and it will appear in next major release in February. What you propose is not backward compatible, so I have to adapt/reject your PR.

The rule is the following for angle and k0l in maps (Survey, Track, Twiss, Emit):

MULTIPOLE:
angle = elm->angle != 0 ? elm->angle : elm->k0l
k0l = elm->k0l

SBEND, RBEND:
angle = elm->angle
k0l = elm->k0 != 0 ? elm->k0*elm->l : elm->angle

Survey: always use angle from above
Track and Twiss: always use k0l from above (and not angle!) and angle-k0l as a field error (added to f_error[0]).

Backward Compatibility:
angle did not exist in multipole and default after introduction is 0 -> BC Ok
so far k0 was ignored in BENDs, but set equal to angle/l in LHC -> BC OK
with above conventions, field error angle-k0l should be 0 -> BC OK

New features:
Multipole as HKicker: elm->angle = 1e-200 (straight), elm->k0l = hkick
Straight Bending magnet: elm->angle = 0, elm->k0 != 0

The only added attribute is angle into MULTIPOLE (already in the dict).

Best,
Laurent.

--
Laurent Deniau                           http://cern.ch/mad
Accelerators Beam Physics        mad@cern.ch<mailto:mad@cern.ch>
CERN, CH-1211 Geneva 23       Tel: +41 (0) 22 767 4647

On 24 Jan 2018, at 18:54, Thomas G. <notifications@github.com<mailto:notifications@github.com>> wrote:


I have implemented this as an alternative for the specific solution suggested in #517<https://github.com/MethodicalAcceleratorDesign/MAD-X/issues/517>, since we also have use for K0L!=angle, specifically in SBEND.

Note that I have added additional KICK attributes to these elements. The main reasons for this choise were:

  *   we prefer a modelling as geometric ANGLE, plus additional KICK. Naming the attribute HKICK should make it clear what it does.
  *   in the case of MULTIPOLE, if we did use the existing ANGLE attribute as suggested in #517<https://github.com/MethodicalAcceleratorDesign/MAD-X/issues/517>, it is not a priori clear what happens for skew multipoles. Is ANGLE always horizontal? Does ANGLE force that only the horizontal reference system is changed, but not the vertical one?
  *   in case of SBEND/RBEND, I wasn't sure about existing use of KNL/K0. Furthermore, using KNL[0] would seem to suggest that KNL[1] etc can be used as well (which is so far not implemented).

However, I'm of course open for discussion about reusing the existing KNL, ANGLE, K0 and whatnot attributes.

I have not yet checked or added tests since I wanted first to wait for the outcome of the discussion.

Best, Thomas

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546

Commit Summary

  *   Add kicks for multipole/bends to support k0l != angle

File Changes

  *   M src/mad_dict.c<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546/files#diff-0> (4)
  *   M src/trrun.f90<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546/files#diff-1> (13)
  *   M src/twiss.f90<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546/files#diff-2> (13)
  *   M src/util.f90<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546/files#diff-3> (1)

Patch Links:

  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546.patch
  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/546.diff

**Comment by coldfix** [comment]
Ok, great. Happy to hear this will be taken care of

**Comment by coldfix** [comment]
> angle = elm->angle != 0 ? elm->angle : elm->k0l

> k0l = elm->k0 != 0 ? elm->k0*elm->l : elm->angle

Why not simply check if the value is set by the user (`par_present` or similar), rather than for its value? Seems a lot cleaner to me.

> The only added attribute is angle into MULTIPOLE (already in the dict).

Currently has default value 1e20, which is somewhat confusing..

**Comment by ldeniau** [comment]
Hi,

On 25 Jan 2018, at 13:01, Thomas G. <notifications@github.com<mailto:notifications@github.com>> wrote:


angle = elm->angle != 0 ? elm->angle : elm->k0l

k0l = elm->k0 != 0 ? elm->k0*elm->l : elm->angle

Why not simply check if the value is set by the user (par_present or similar), rather than for its value? Seems a lot cleaner to me.

Because we need to retrieve the values anyway for further calculation, so it’s faster and better for backward compatibility to check vs values. (and my confidence in the integrity in this unmanaged forest of pointers is somehow limited).


The only added attribute is angle into MULTIPOLE (already in the dict).

Currently has default value 1e20, which is somewhat confusing..

This was an old attempt and disappeared in my local commits (back to 0).

Cheers,
Laurent.

**Pull request closed without merging**
