### PR TITLE
Change to use magnet strength instead of angle to define fringe

### PR DESCRIPTION
**Pull request by tpersson**

### CODE REVIEW

**Comment by rdemaria** [comment]
I think to remember there is a part that depends on h and one on k0. Have you verified with mad8 physics guide?

**Comment by tpersson** [comment]
I know that one depends on k0 and one h for the weak focusing (what I updated a few month ago) but for the fringe fields I thought it was only the B0 and of course the pole-face angles but very possible I am missing something here.

**Comment by tpersson** [comment]
http://pcwww.liv.ac.uk/~awolski/Teaching/Cockcroft/LinearDynamics/LinearDynamics-Lecture5.pdf

Normally Wolski differentiates between h and k0 and he seems to be using k0 as well..

**Comment by rdemaria** [comment]
Mad8 physical guide uses h and the field integral I1, instead. I think it is worth investigating further.

**Comment by rdemaria** [comment]
There is also this reference which distinguish orbit and field https://link.aps.org/pdf/10.1103/PhysRevSTAB.18.122401
introducing new terms.

Wolski reference is for the hard edge, but I agree using the filed looks more correct.

**Comment by chernals** [comment]
I agree with the change proposed by Tobias, I cannot see why this wouldn't be correct (except for the fact that having a different field than the one producing the geometrical curvature radius kind of implicitly defines an edge angle... but that might be higher-order only, I'm a bit confused with that).

Also, I think this is closely related to issue #847 I believe. Having a different reference DPP or changing the K0 is equivalent.

**Pull request merged**
