### PR TITLE
Updates the tests and build on travis

### PR DESCRIPTION
**Pull request by tpersson**
This builds on Travis and on my machine.

### CODE REVIEW

**Comment by ldeniau** [comment]
Hi Tobias,

I added many fallthrough in the code to remove warnings. Why did you remove it as anyway it is supported by C++11 and we decided to move to C++11 as the minimal level of C++?

Cheers,
Laurent.

On 14 Feb 2018, at 16:24, tpersson <notifications@github.com<mailto:notifications@github.com>> wrote:


This builds on Travis and on my machine.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568

Commit Summary

  *   Uptated some cfg files to pass some tests.
  *   Merge branch 'master' of github.com<http://github.com>:MethodicalAcceleratorDesign/MAD-X into fixTestsAfterThin
  *   Added a check to the __atribute__
  *   comment fallthrough.

File Changes

  *   M src/mad_mkthin.cpp<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-0> (3)
  *   M tests/test-twiss-4/test-twiss-4.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-1> (6)
  *   M tests/test-twiss-4/twiss.b2.data.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-2> (2)
  *   M tests/test-twiss-8/thin.seq.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-3> (2)

Patch Links:

  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568.patch
  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568.diff

**Comment by ldeniau** [comment]
We maybe need to upgrade the compilers versions on the server and/or Travis to get proper support of fallthrough attribute.

Cheers,
Laurent.

On 14 Feb 2018, at 20:13, Laurent Deniau <Laurent.Deniau@cern.ch<mailto:Laurent.Deniau@cern.ch>> wrote:

Hi Tobias,

I added many fallthrough in the code to remove warnings. Why did you remove it as anyway it is supported by C++11 and we decided to move to C++11 as the minimal level of C++?

Cheers,
Laurent.

On 14 Feb 2018, at 16:24, tpersson <notifications@github.com<mailto:notifications@github.com>> wrote:


This builds on Travis and on my machine.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568

Commit Summary

  *   Uptated some cfg files to pass some tests.
  *   Merge branch 'master' of github.com<http://github.com/>:MethodicalAcceleratorDesign/MAD-X into fixTestsAfterThin
  *   Added a check to the __atribute__
  *   comment fallthrough.

File Changes

  *   M src/mad_mkthin.cpp<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-0> (3)
  *   M tests/test-twiss-4/test-twiss-4.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-1> (6)
  *   M tests/test-twiss-4/twiss.b2.data.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-2> (2)
  *   M tests/test-twiss-8/thin.seq.cfg<https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568/files#diff-3> (2)

Patch Links:

  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568.patch
  *   https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/568.diff

**Comment by tpersson** [comment]
It is actually not removed. It is a different syntax that is ignored in not supported versions. It is strange because Travis says it uses version 7.2 so I am not sure why it doesn't work.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by tpersson** [comment]
What is not clear to me is why it crashed for this one but it seems to work fine for the rest.

**Comment by ldeniau** [comment]
It may be related to the fact that this one is the only one in C++ code, the others are in C99 code?

**Pull request merged**
