### PR TITLE
IBS Table Fix and Code Source Comments

### PR DESCRIPTION
**Pull request by fsoubelet**
Hello,

Since I have looked at the IBS module source code (ibsdb.f90) quite a lot for work recently, I figured it would be beneficial to submit a PR with an "improved" (as much as I could) documentation of this module.

**Important point: No code change is made in this PR.**

All this PR brings is a lot of comments trying to explain:
  - What do things correspond to (variables, mostly)
  - What is being done
  - Why it is being done (sometimes)

I'm not 100% sure I am correct on everything in here, but almost all my additions should be correct and, hopefully, helpful.

### CODE REVIEW

**Review by rdemaria — APPROVED** [review]
ok to me, waiting for the tests to run

**Comment by fsoubelet** [comment]
I've made just a few corrections / additions.

Interesting to note, that I forgot to mention initially: it seems (empirically, to me) that the IBS table is only created internally when the command is called with a value for an output file (`ibs, file="string";`) and not otherwise. This is note what is written in the user guide (currently, end of page 198) which implies the table is always created.

**Comment by rdemaria** [comment]
Feel free to create the table anyway if it is helpful for your use case.

**Comment by fsoubelet** [comment]
Hi @rdemaria 

- I have tried to force the IBS table to be written by removing the check for the `ibs_table` option and the related if check before writing to table (lines 151 and then 250 to 260) but to no avail. Maybe there is something more done on the C side that creates the table and sets this `ibs_table` flag? It is not one given by the IBS command.

- I have made a small addition (lines 554-556) so that both the coulomb logarithm and the full constant of Eq (8) of the note are exported to the global namespace, as `ibs.coulog` and `ibs.const`, respectively.

**Comment by rdemaria** [comment]
Yes please add two lines to the manual if it.is easy to do so...

**Comment by fsoubelet** [comment]
Done! I have also brought in a little correction about the `txi, `tyi` and `tli` terms found in the `IBS` table, since it was mentioned that they are the "intermediate" growth rates but they are not.

Let me know if this looks alright to you @rdemaria

**Comment by fsoubelet** [comment]
@rdemaria I'm not sure what went wrong with this single Windows build, but it seems it received an interrupt signal due to the runtime timeout of 30min defined in the workflow file (currently line 176).

Would it be possible to try reruning just this one? I'm fairly confident it would pass just fine.

**Review by rdemaria — APPROVED** [review]

**Pull request merged**
