### PR TITLE
Changed type and length of aperture elements in sixtrack output

### PR DESCRIPTION
**Pull request by vkbo**
The element number for aperture in the fort.2 export was set to 3 (sextupole it seems) with a length of 10 nm. As far @JamesMolson or I could tell, there is no reason why this should not be type 0 with length 0.0; which is what SixTrack expects.

### CODE REVIEW

**Comment by vkbo** [comment]
Ah, this of course breaks the test on fc.2 as the reference file now differs.

**Comment by rdemaria** [comment]
why was this changed?

**Comment by ldeniau** [comment]
because the type of the element exported seems to not be the right one according to Veronica, and the length seems weird…

It would be nice that persons working on SixTrack communicate with MAD-X team on the basis of specifications discussed by both teams (SixTrack and MAD-X), then providing a PR is of course very welcome. This would avoid bad moves between codes.

Laurent.

--
Laurent Deniau                           http://cern.ch/mad
Accelerators Beam Physics        mad@cern.ch<mailto:mad@cern.ch>
CERN, CH-1211 Geneva 23       Tel: +41 (0) 22 767 4647

On 01 Feb 2018, at 21:50, Riccardo De Maria <notifications@github.com<mailto:notifications@github.com>> wrote:

why was this changed?

**Comment by vkbo** [comment]
The fc.2.ref file has now been updated with the correct values for my fix. It just passed the tests.

**Pull request merged**
